Repository worknenjoy/gitpay, pull requests merged in 2025-06, with the labels that each got.

#1205 Fix typos
  deploy-ghpages.sh
  frontend/README.md
  frontend/src/components/areas/private/features/payments/checkout/checkout-form.js
  frontend/src/components/areas/private/features/transfers/transfers.js
  frontend/src/components/areas/private/shared/messages.js
  frontend/src/components/areas/public/features/task/offers/task-offer-drawer.tsx
  frontend/src/components/areas/public/features/task/task-assignment.js
  frontend/src/components/areas/public/features/task/task-report.js
  frontend/src/components/areas/public/features/welcome/legacy/landing-page.js
  frontend/src/components/areas/public/features/welcome/legacy/messages.js
  frontend/src/components/design-library/molecules/dialogs/issue-reports-dialog/issue-reports-dialog.tsx
  frontend/src/translations/en.json
  frontend/src/translations/generated/en.json
  frontend/src/translations/result/en.json
  frontend/webpack.config.js
  scripts.js
Labels: documentation

#1209 Refactor checkbox terms styles
  frontend/src/components/design-library/atoms/inputs/checkbox-terms/checkbox-terms.styles.ts
  frontend/src/components/design-library/atoms/inputs/checkbox-terms/checkbox-terms.tsx
Labels: refactoring, codex

#1211 Add eslint rules
  .eslintrc
  package-lock.json
  package.json
Labels: dependencies, codex

#1212 Split actions tests by module
  frontend/tests/actions/actions.test.js
  frontend/tests/actions/contactActions.test.js
  frontend/tests/actions/organizationsActions.test.js
  frontend/tests/actions/preferencesActions.test.js
  frontend/tests/actions/taskActions.test.js
Labels: testing, codex

#1215 Improve docs translations
  _docs/en/assets.md
  _docs/en/configuration.md
  _docs/en/posts.md
  _docs/en/structure.md
  _docs/en/usage.md
Labels: documentation, codex

#1217 docs: edited the license link
  README.md
Labels: documentation

#1223 Move component tests next to sources
  frontend/src/components/areas/private/components/session/__tests__/login-form.test.jsx
  frontend/src/components/areas/private/features/payments/legacy/checkout/__tests__/checkout.test.js
  frontend/src/components/areas/public/features/task/__tests__/messageAuthor.test.js
  frontend/src/components/areas/public/features/task/components/__tests__/task-solution-drawer.test.js
  frontend/src/components/design-library/molecules/cards/team-card/__tests__/cardTeam.test.js
Labels: refactoring, codex

#1230 New Crowdin updates
  locales/result/br.json
Labels: content
