Repository worknenjoy/gitpay, pull requests merged in 2025-07, with the labels that each got.

#1228 Fix/fixing tests
  .circleci/config.yml
  config/passport.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/actions/loginActions.js
  frontend/src/components/areas/private/features/payments/legacy/checkout/__tests__/checkout.test.js
  frontend/src/components/areas/private/features/payments/legacy/checkout/address-section.js
  frontend/src/components/areas/private/features/payments/legacy/checkout/card-section.js
  frontend/src/components/areas/private/features/payments/legacy/checkout/checkout-form.js
  frontend/src/components/areas/private/features/payments/legacy/checkout/stripe-checkout.js
  frontend/src/components/areas/public/features/task/__tests__/messageAuthor.test.js
  frontend/src/components/design-library/molecules/cards/team-card/__tests__/cardTeam.test.js
  frontend/src/index.html
  frontend/stripe-v3.js
  index.js
  modules/app/controllers/auth.js
  modules/app/controllers/webhook.js
  modules/app/index.js
  modules/app/routes/secure.js
  modules/orders/orderBuilds.js
  modules/orders/orderRefund.js
  modules/orders/orderUpdate.js
  modules/paymentRequests/paymentRequestBuilds.js
  modules/shared/stripe/stripe.js
  modules/tasks/taskPayment.js
  modules/tasks/taskTransfer.js
  modules/tasks/taskUpdate.js
  modules/transfers/transferBuilds.js
  modules/transfers/transferFetch.js
  modules/transfers/transferUpdate.js
  modules/users/userAccount.js
  modules/users/userAccountCountries.js
  modules/users/userAccountCreate.js
  modules/users/userBankAccount.js
  modules/users/userBankAccountCreate.js
  modules/users/userBankAccountUpdate.js
  modules/users/userCustomer.js
  modules/users/userCustomerCreate.js
  modules/users/userCustomerUpdate.js
  modules/users/userExists.js
  modules/users/userFetch.js
  modules/util/customer.js
  modules/walletOrders/walletOrderBuilds.js
  modules/walletOrders/walletOrderFetch.js
  modules/webhooks/checkoutSessionCompleted.js
  package-lock.json
  package.json
  scripts.js
  server.js
  test/helpers/index.js
  test/order.test.js
  test/payment-requests.test.js
  test/ping.test.js
  test/scripts.test.js
  test/user.test.js
  test/webhook.test.js
Labels: testing, dependencies, refactoring

#1234 test: separate webhook platform and connect tests
  test/webhook.connect.test.js
  test/webhook.platform.test.js
Labels: testing, refactoring

#1231 feat: add filters to public explore page
  frontend/src/components/areas/public/features/task/language-filter.stories.tsx
  frontend/src/components/areas/public/features/task/task-explorer.js
  frontend/src/components/areas/public/features/task/task-filter-labels.stories.tsx
  frontend/src/components/areas/public/features/task/task-filters.stories.tsx
  frontend/src/containers/task-explorer.js
Labels: feature, testing, react

#1236 Migrate paymentstatus basestatus
  frontend/src/components/areas/private/features/payments/legacy/payments.js
  frontend/src/components/areas/private/features/wallets/wallets.tsx
  frontend/src/components/design-library/atoms/status/payment-types-status/invoice-status/invoice-status.stories.tsx
  frontend/src/components/design-library/atoms/status/payment-types-status/invoice-status/invoice-status.tsx
  frontend/src/components/design-library/atoms/status/payment-types-status/payment-status/payment-status.stories.tsx
  frontend/src/components/design-library/atoms/status/payment-types-status/payment-status/payment-status.styles.ts
  frontend/src/components/design-library/atoms/status/payment-types-status/payment-status/payment-status.tsx
Labels: refactoring

#1237 Fix label/language search query
  modules/app/controllers/label.js
  modules/app/controllers/language.js
  modules/app/controllers/task.js
Labels: testing, node.js, codex

#1239 Refactor webhook platform handlers
  modules/app/controllers/webhooks/webhook-platform.js
  modules/webhooks/balanceAvailable.js
  modules/webhooks/chargeFailed.js
  modules/webhooks/chargeRefunded.js
  modules/webhooks/chargeUpdated.js
  modules/webhooks/constants.js
  modules/webhooks/customerSourceCreated.js
  modules/webhooks/invoiceCreated.js
  modules/webhooks/invoiceFinalized.js
  modules/webhooks/invoicePaid.js
  modules/webhooks/invoicePaymentFailed.js
  modules/webhooks/invoicePaymentSucceeded.js
  modules/webhooks/invoiceUpdated.js
  modules/webhooks/payoutCreated.js
  modules/webhooks/payoutFailed.js
  modules/webhooks/payoutPaid.js
  modules/webhooks/transferCreated.js
Labels: refactoring, codex

#1249 supporting mobile menu for private pages
  frontend/src/components/areas/private/components/profile-sidebar.tsx
  frontend/src/components/design-library/molecules/menus/side-menu/side-menu-items.tsx
  frontend/src/components/design-library/molecules/menus/side-menu/side-menu.styled.div.js
  frontend/src/components/design-library/molecules/menus/side-menu/side-menu.tsx
Labels: enhancement, refactoring

#1255 assigning current user session for all task solution endpoints
  frontend/src/actions/taskSolutionActions.js
  frontend/src/components/areas/public/features/task/components/send-solution-drawer.tsx
  frontend/src/containers/send-solution-drawer.js
  modules/app/controllers/taskSolution.js
  test/taskSolution.test.js
Labels: testing, API
