Repository worknenjoy/gitpay, pull requests merged in 2025-09, with the labels that each got.

#1264 New Crowdin updates
  frontend/src/translations/result/br.json
  frontend/src/translations/result/en.json
Labels: content

#1268 handling amount convertion in centavos
  modules/util/handle-amount/handle-amount.js
  test/handle-amount.test.js
Labels: testing

#1266 New Crowdin updates
  frontend/src/translations/result/br.json
  frontend/src/translations/result/en.json
Labels: content

#1270 new payment status and transfer components
  frontend/src/components/areas/private/features/claims/claims.tsx
  frontend/src/components/areas/private/features/payouts/payouts-table.tsx
  frontend/src/components/design-library/atoms/status/payout-status/payout-status.stories.tsx
  frontend/src/components/design-library/atoms/status/payout-status/payout-status.styles.ts
  frontend/src/components/design-library/atoms/status/payout-status/payout-status.tsx
  frontend/src/components/design-library/atoms/status/transfer-status/transfer-status.stories.tsx
  frontend/src/components/design-library/atoms/status/transfer-status/transfer-status.styles.ts
  frontend/src/components/design-library/atoms/status/transfer-status/transfer-status.tsx
  frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/payouts/payout-status-field/payout-status-field.stories.tsx
  frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/payouts/payout-status-field/payout-status-field.tsx
  frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/transfer/transfer-status-field/transfer-status-field.stories.tsx
  frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/transfer/transfer-status-field/transfer-status-field.tsx
Labels: enhancement, testing

#1271 Fix typos
  frontend/src/translations/generated/en.json
  modules/app/controllers/webhook.js
Labels: content

#1273 handling reversed transfers
  modules/app/controllers/webhooks/webhook-connect.js
  modules/app/controllers/webhooks/webhook-platform.js
  modules/webhooks/transferReversed.js
  scripts/webhook_script.js
  test/data/stripe/stripe.webhook.transfer.reversed.js
  test/webhook.connect.test.js
  test/webhook.platform.test.js
Labels: testing, API

#1272 New Crowdin updates
  frontend/src/translations/result/br.json
  frontend/src/translations/result/en.json
Labels: content
