Repository worknenjoy/gitpay, pull requests merged in 2025-02, with the labels that each got.

#1172 Feat/fees revisited
  frontend/src/components/design-library/molecules/pickup-tag-list/pickup-tag-list.stories.jsx
  frontend/src/components/design-library/molecules/pickup-tag-list/pickup-tag-list.tsx
  frontend/src/components/design-library/molecules/plan-card/plan-card.tsx
  frontend/src/components/task/payment/methods/invoice/payment-method-invoice-tab.tsx
  frontend/src/components/task/task-payment-form.js
  frontend/src/components/welcome/pricing.js
  migration/migrations/20250129165212-create-plan-schema.js
  migration/migrations/20250129170625-add-plan-schemas-to-plans.js
  migration/migrations/20250129201839-add-create-at-updated-at-to-plan.js
  migration/seeders/20250130160328-create-plan-schemas.js
  models/plan.js
  models/planSchema.js
  models/wallet.js
  modules/orders/orderBuilds.js
  test/order.test.js
  test/task.test.js
Labels: enhancement, feature, database

#1174 Feat/side-menu-revisited
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/design-library/atoms/field/field.tsx
  frontend/src/components/design-library/molecules/input-comment/input-comment.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-created-field/issue-created-field.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-created-field/issue-created-field.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-labels-field/issue-labels-field.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-labels-field/issue-labels-field.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-language-field/issue-language-field.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-language-field/issue-language-field.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-link-field/issue-link-field.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-link-field/issue-link-field.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-price-field/issue-price-field.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-price-field/issue-price-field.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-project-field/issue-project-field.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-project-field/issue-project-field.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-status-field/issue-status-field.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table-custom-fields/issue-status-field/issue-status-field.tsx
  frontend/src/components/design-library/molecules/section-table/section-table.stories.tsx
  frontend/src/components/design-library/molecules/section-table/section-table.tsx
  frontend/src/components/design-library/molecules/side-menu/side-menu.stories.tsx
  frontend/src/components/design-library/molecules/side-menu/side-menu.tsx
  frontend/src/components/design-library/organisms/delivery-date/delivery-date.tsx
  frontend/src/components/profile/account-customer.tsx
  frontend/src/components/profile/account-details.tsx
  frontend/src/components/profile/bank-account.tsx
  frontend/src/components/profile/components/account-header.tsx
  frontend/src/components/profile/components/account-tab-main.tsx
  frontend/src/components/profile/components/payments/payouts/bank-account-settings.tsx
  frontend/src/components/profile/components/wallets/wallet-form.tsx
  frontend/src/components/profile/explore/explore-issues-table.tsx
  frontend/src/components/profile/my-skill.js
  frontend/src/components/profile/preferences.js
  frontend/src/components/profile/preferences.tsx
  frontend/src/components/profile/profile-sidebar.tsx
  frontend/src/components/profile/profile.js
  frontend/src/components/profile/settings.js
  frontend/src/components/profile/settings.tsx
  frontend/src/components/profile/skill.tsx
  frontend/src/components/profile/user-explore-tasks.tsx
  frontend/src/components/profile/user-tasks.js
  frontend/src/components/profile/wallets-table.js
  frontend/src/components/profile/wallets-table.tsx
  frontend/src/components/profile/wallets.tsx
  frontend/src/components/task/payment/methods/invoice/payment-method-invoice-tab.tsx
  frontend/src/components/task/task-assignment.js
  frontend/src/components/task/task-deadline-form.js
  frontend/src/components/task/task-header-metadata.jsx
  frontend/src/components/task/task-list.tsx
  frontend/src/components/task/task-order-invoice-confirm.tsx
  frontend/src/components/task/task-table.js
  frontend/src/components/topbar/import-issue-dialog.tsx
  frontend/src/components/welcome/home.js
  frontend/src/consts.ts
  frontend/src/containers/user-tasks-explore.js
  frontend/src/main/app.js
  frontend/src/translations/generated/br.json
  frontend/src/translations/generated/en.json
  frontend/tsconfig.json
Labels: react, dependencies, refactoring

#1176 fix:fix bug where phone field clears on accepting terms
  frontend/src/components/profile/TextMaskCustom.tsx
  frontend/src/components/profile/account-details.tsx
Labels: bug, refactoring

#1175 New Crowdin updates
  frontend/src/translations/result/br.json
  frontend/src/translations/result/en.json
Labels: content

#1179 New Crowdin updates
  frontend/src/translations/result/en.json
Labels: content
