Repository worknenjoy/gitpay, pull requests merged in 2025-01, with the labels that each got.

#1164 New Crowdin updates
  frontend/src/translations/result/br.json
  frontend/src/translations/result/en.json
Labels: content

#1166 Add TaskDeadlineDrawer
  frontend/src/components/design-library/templates/task-deadline-drawer/task-deadline-drawer.tsx
  frontend/src/components/task/task-deadline-form.js
  frontend/src/components/task/task.js
  frontend/src/translations/br.json
  frontend/src/translations/en.json
  frontend/src/translations/generated/br.json
  frontend/src/translations/generated/en.json
Labels: enhancement

#1167 New Crowdin updates
  frontend/src/translations/result/br.json
  frontend/src/translations/result/en.json
Labels: content

#1168 Feat/programing languages filter for projects
  frontend/src/actions/languageActions.js
  frontend/src/components/task/language-filter.tsx
  frontend/src/components/task/task-table.js
  migration/migrations/20241228170105-create-programming-languages-tables.js
  models/programminglanguage.js
  models/project.js
  models/projectProgrammingLanguage.js
  models/task.js
  modules/app/controllers/language.js
  modules/app/routes/language.js
  modules/language/index.js
  modules/language/projectProgrammingLanguage.js
  modules/tasks/taskBuilds.js
  modules/tasks/taskSearch.js
  scripts/update_projects_programming_languages.js
Labels: feature, database
